import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = typeof pkg.version === 'string' ? pkg.version : '';
if (!version) throw new Error('package.json must include a non-empty "version" string.');

const rawNotes = JSON.parse(readFileSync(join(root, 'src/release-notes.json'), 'utf8'));
const notes = Array.isArray(rawNotes) ? rawNotes.map(String) : [];

const versionPayload = {
  version,
  notes,
  maintenanceNote:
    'Generated by scripts/prebuild.mjs from package.json and src/release-notes.json. Bump the 4-part "version" in package.json by hand (npm version cannot parse it), edit src/release-notes.json, then npm run build.',
};

const swVersionRe = /const APP_VERSION = '[^']*'/;

function injectSw(source) {
  if (!swVersionRe.test(source)) throw new Error('prebuild: could not find APP_VERSION line in sw.js');
  return source.replace(swVersionRe, `const APP_VERSION = '${version}'`);
}

// Only files under public/ are copied into dist, so those are the only copies
// that ship. Keeping duplicates at the repo root meant edits could silently
// never deploy.
const swPath = join(root, 'public/sw.js');
writeFileSync(swPath, injectSw(readFileSync(swPath, 'utf8')), 'utf8');

writeFileSync(join(root, 'public/version.json'), JSON.stringify(versionPayload, null, 2) + '\n', 'utf8');

const indexPath = join(root, 'index.html');
let html = readFileSync(indexPath, 'utf8');
const metaRe = /<meta name="app-version" content="[^"]*" \/>/;
if (!metaRe.test(html)) throw new Error('prebuild: app-version meta not found in index.html');
html = html.replace(metaRe, `<meta name="app-version" content="${version}" />`);
writeFileSync(indexPath, html, 'utf8');

console.log(`prebuild: synced ${version} → public/sw.js, public/version.json, index.html`);
