#!/usr/bin/env node
// Reads version from package.json and notes from src/release-notes.json, then
// propagates them to sw.js, public/sw.js, version.json, public/version.json,
// and the <meta name="app-version"> tag in index.html.
// Run automatically as part of "npm run build". No manual edits needed elsewhere.

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const pkg   = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const notes = JSON.parse(readFileSync(resolve(root, 'src/release-notes.json'), 'utf8'));
const version = pkg.version;

console.log(`[prebuild] version = ${version}`);

// sw.js + public/sw.js: replace the APP_VERSION line
for (const rel of ['sw.js', 'public/sw.js']) {
  const p = resolve(root, rel);
  const updated = readFileSync(p, 'utf8')
    .replace(/^const APP_VERSION = '[^']*';/m, `const APP_VERSION = '${version}';`);
  writeFileSync(p, updated);
  console.log(`[prebuild] updated ${rel}`);
}

// version.json + public/version.json
const versionJson = JSON.stringify({
  version,
  maintenanceNote: 'Auto-generated by scripts/prebuild.mjs. Edit version in package.json, notes in src/release-notes.json.',
  notes
}, null, 2) + '\n';

for (const rel of ['version.json', 'public/version.json']) {
  writeFileSync(resolve(root, rel), versionJson);
  console.log(`[prebuild] wrote ${rel}`);
}

// index.html: update <meta name="app-version" content="...">
const htmlPath = resolve(root, 'index.html');
const html = readFileSync(htmlPath, 'utf8')
  .replace(/(<meta name="app-version" content=")[^"]*(")/,  `$1${version}$2`);
writeFileSync(htmlPath, html);
console.log(`[prebuild] updated index.html`);
